services:
  nestjs:
    build: .
    container_name: nest_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
